Make contents of `__init__.py` equal across projects
databricks/databricks-sql-python pull request #304
Opened 2023-12-21 11:05 UTC by pietern

2023-12-21 16:47 UTC, andrefurlan-db approved these changes

2023-12-21 16:49 UTC, susodapop requested changes
We're moving off of `unittest` towards pytest. I can push a refactor of this unit test using pytest later today.

2023-12-21 16:59 UTC, susodapop approved these changes
I updated the unit test to use pytest

2023-12-22 09:48 UTC, pietern commented
Thanks! Then this is ready to merge. Could you click the merge button? (I don't have write access)

2023-12-26 15:19 UTC, merged