Fix logging statements in oauth.py
databricks/databricks-sql-python pull request #93
Opened 2023-03-07 23:48 UTC by jbylund

* fix a couple logging statements (lazy parameters, right number of args), left one as a string interpolation because the message is also used in an exception
* add some timeouts to http requests

2023-07-12 21:48 UTC, susodapop requested changes
Sorry if I'm being foggy-brained here, but apart from the timeouts I'm not clear what this PR actually changes? The log messages appear to be the same, but using the older string interpolation syntax. For this repository f-strings are the preferred direction.

2023-07-12 21:48 UTC, susodapop commented on src/databricks/sql/auth/oauth.py
> +                "Unable to fetch OAuth configuration from %s.\n"
Why the change from f-strings throughout?

2023-07-12 21:48 UTC, susodapop commented on src/databricks/sql/auth/oauth.py
> +            response = requests.get(url=known_config_url, timeout=10)
Generally we like to keep these timeouts configurable. Perhaps when instantiating the OAuthManager?

2023-07-12 22:39 UTC, jbylund commented
> Sorry if I'm being foggy-brained here, but apart from the timeouts I'm not clear what this PR actually changes? The log messages appear to be the same, but using the older string interpolation syntax. For this repository f-strings are the preferred direction.

I had assumed %-formatting and passing args to the logging call would be preferred because that's the recommended pattern for logging. I think there are some benefits to using %-formatting for logging calls (it's lazy which helps performance and makes writing log handlers easier).

I don't need this pr any longer (and it's got a conflict now), so unless you want to change the logging style I'll just close this. If you would like to change the logging formatting repo wide I'd be happy to take that on and maybe add a check to the ci pipeline.

2023-07-13 00:59 UTC, jbylund commented on src/databricks/sql/auth/oauth.py
> -                logger.error("unexpected error", e)
This is probably the issue that brought me here in the first place. The format string here has no positions for arguments, but one argument was provided.

2023-07-14 19:27 UTC, susodapop commented
I think for now we should certainly fix the failed logging statement on line 113 (marker included but no value provided). I can do that with this current PR so you get the contribution credit or we can file it as a follow-up. Any preference?

2023-11-01 01:08 UTC, susodapop commented
Closing in favour of #269. This change will be part of the next release.

2023-11-01 01:08 UTC, closed without merging